// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0
#include "MATHLIB_cos_testParams.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1) || defined(DEMO_CASE))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2) || defined(DEMO_CASE))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3) || defined(DEMO_CASE))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4) || defined(DEMO_CASE))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5) || defined(DEMO_CASE))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6) || defined(DEMO_CASE))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7) || defined(DEMO_CASE))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8) || defined(DEMO_CASE))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9) || defined(DEMO_CASE))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10) || defined(DEMO_CASE))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11) || defined(DEMO_CASE))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12) || defined(DEMO_CASE))
#include "test_data/staticRefCase12.h"
#endif

static MATHLIB_cos_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1) || defined(DEMO_CASE))
    {
        staticRefInCase1,  // Input vector
        staticRefOutCase1, // Output vector
        1,                 // length of vector
        MATHLIB_FLOAT32,   // precision
        1,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2) || defined(DEMO_CASE))
    {
        staticRefInCase2,  // Input vector
        staticRefOutCase2, // Output vector
        15,                // length of vector
        MATHLIB_FLOAT32,   // precision
        2,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3) || defined(DEMO_CASE))
    {
        staticRefInCase3,  // Input vector
        staticRefOutCase3, // Output vector
        128,               // length of vector
        MATHLIB_FLOAT32,   // precision
        3,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4) || defined(DEMO_CASE))
    {
        staticRefInCase4,  // Input vector
        staticRefOutCase4, // Output vector
        512,               // length of vector
        MATHLIB_FLOAT32,   // precision
        4,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5) || defined(DEMO_CASE))
    {
        staticRefInCase5,  // Input vector
        staticRefOutCase5, // Output vector
        1024,              // length of vector
        MATHLIB_FLOAT32,   // precision
        5,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6) || defined(DEMO_CASE))
    {
        staticRefInCase6,  // Input vector
        staticRefOutCase6, // Output vector
        2048,              // length of vector
        MATHLIB_FLOAT32,   // precision
        6,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7) || defined(DEMO_CASE))
    {
        staticRefInCase7,  // Input vector
        staticRefOutCase7, // Output vector
        1,                 // length of vector
        MATHLIB_FLOAT64,   // precision
        7,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8) || defined(DEMO_CASE))
    {
        staticRefInCase8,  // Input vector
        staticRefOutCase8, // Output vector
        15,                // length of vector
        MATHLIB_FLOAT64,   // precision
        8,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9) || defined(DEMO_CASE))
    {
        staticRefInCase9,  // Input vector
        staticRefOutCase9, // Output vector
        128,               // length of vector
        MATHLIB_FLOAT64,   // precision
        9,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10) || defined(DEMO_CASE))
    {
        staticRefInCase10,  // Input vector
        staticRefOutCase10, // Output vector
        512,                // length of vector
        MATHLIB_FLOAT64,    // precision
        10,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11) || defined(DEMO_CASE))
    {
        staticRefInCase11,  // Input vector
        staticRefOutCase11, // Output vector
        1024,               // length of vector
        MATHLIB_FLOAT64,    // precision
        11,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12) || defined(DEMO_CASE))
    {
        staticRefInCase12,  // Input vector
        staticRefOutCase12, // Output vector
        2048,               // length of vector
        MATHLIB_FLOAT64,    // precision
        12,                 // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void MATHLIB_cos_getTestParams(MATHLIB_cos_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(MATHLIB_cos_testParams_t);
}
