// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0
#include "MATHLIB_atan2_testParams.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1) || defined(DEMO_CASE))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2) || defined(DEMO_CASE))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3) || defined(DEMO_CASE))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4) || defined(DEMO_CASE))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5) || defined(DEMO_CASE))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6) || defined(DEMO_CASE))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7) || defined(DEMO_CASE))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12) || defined(DEMO_CASE))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13) || defined(DEMO_CASE))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14) || defined(DEMO_CASE))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15) || defined(DEMO_CASE))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16) || defined(DEMO_CASE))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17) || defined(DEMO_CASE))
#include "test_data/staticRefCase17.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18) || defined(DEMO_CASE))
#include "test_data/staticRefCase18.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
#include "test_data/staticRefCase19.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
#include "test_data/staticRefCase20.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
#include "test_data/staticRefCase21.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
#include "test_data/staticRefCase22.h"
#endif

static MATHLIB_atan2_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1) || defined(DEMO_CASE))
    {
        staticRefIn0Case1, // Input vector 0
        staticRefIn1Case1, // Input vector 1
        staticRefOutCase1, // Output vector
        1,                 // length of vector
        MATHLIB_FLOAT32,   // precision
        1,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2) || defined(DEMO_CASE))
    {
        staticRefIn0Case2, // Input vector 0
        staticRefIn1Case2, // Input vector 1
        staticRefOutCase2, // Output vector
        15,                // length of vector
        MATHLIB_FLOAT32,   // precision
        2,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3) || defined(DEMO_CASE))
    {
        staticRefIn0Case3, // Input vector 0
        staticRefIn1Case3, // Input vector 1
        staticRefOutCase3, // Output vector
        128,               // length of vector
        MATHLIB_FLOAT32,   // precision
        3,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4) || defined(DEMO_CASE))
    {
        staticRefIn0Case4, // Input vector 0
        staticRefIn1Case4, // Input vector 1
        staticRefOutCase4, // Output vector
        256,               // length of vector
        MATHLIB_FLOAT32,   // precision
        4,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5) || defined(DEMO_CASE))
    {
        staticRefIn0Case5, // Input vector 0
        staticRefIn1Case5, // Input vector 1
        staticRefOutCase5, // Output vector
        512,               // length of vector
        MATHLIB_FLOAT32,   // precision
        5,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6) || defined(DEMO_CASE))
    {
        staticRefIn0Case6, // Input vector 0
        staticRefIn1Case6, // Input vector 1
        staticRefOutCase6, // Output vector
        1024,              // length of vector
        MATHLIB_FLOAT32,   // precision
        6,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7) || defined(DEMO_CASE))
    {
        staticRefIn0Case7, // Input vector 0
        staticRefIn1Case7, // Input vector 1
        staticRefOutCase7, // Output vector
        2048,              // length of vector
        MATHLIB_FLOAT32,   // precision
        7,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        staticRefIn0Case8, // Input vector 0
        staticRefIn1Case8, // Input vector 1
        staticRefOutCase8, // Output vector
        10240,             // length of vector
        MATHLIB_FLOAT32,   // precision
        8,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        staticRefIn0Case9, // Input vector 0
        staticRefIn1Case9, // Input vector 1
        staticRefOutCase9, // Output vector
        550,               // length of vector
        MATHLIB_FLOAT32,   // precision
        9,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        staticRefIn0Case10, // Input vector 0
        staticRefIn1Case10, // Input vector 1
        staticRefOutCase10, // Output vector
        1090,               // length of vector
        MATHLIB_FLOAT32,    // precision
        10,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        staticRefIn0Case11, // Input vector 0
        staticRefIn1Case11, // Input vector 1
        staticRefOutCase11, // Output vector
        2500,               // length of vector
        MATHLIB_FLOAT32,    // precision
        11,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12) || defined(DEMO_CASE))
    {
        staticRefIn0Case12, // Input vector 0
        staticRefIn1Case12, // Input vector 1
        staticRefOutCase12, // Output vector
        1,                  // length of vector
        MATHLIB_FLOAT64,    // precision
        12,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13) || defined(DEMO_CASE))
    {
        staticRefIn0Case13, // Input vector 0
        staticRefIn1Case13, // Input vector 1
        staticRefOutCase13, // Output vector
        15,                 // length of vector
        MATHLIB_FLOAT64,    // precision
        13,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14) || defined(DEMO_CASE))
    {
        staticRefIn0Case14, // Input vector 0
        staticRefIn1Case14, // Input vector 1
        staticRefOutCase14, // Output vector
        128,                // length of vector
        MATHLIB_FLOAT64,    // precision
        14,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15) || defined(DEMO_CASE))
    {
        staticRefIn0Case15, // Input vector 0
        staticRefIn1Case15, // Input vector 1
        staticRefOutCase15, // Output vector
        256,                // length of vector
        MATHLIB_FLOAT64,    // precision
        15,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16) || defined(DEMO_CASE))
    {
        staticRefIn0Case16, // Input vector 0
        staticRefIn1Case16, // Input vector 1
        staticRefOutCase16, // Output vector
        512,                // length of vector
        MATHLIB_FLOAT64,    // precision
        16,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17) || defined(DEMO_CASE))
    {
        staticRefIn0Case17, // Input vector 0
        staticRefIn1Case17, // Input vector 1
        staticRefOutCase17, // Output vector
        1024,               // length of vector
        MATHLIB_FLOAT64,    // precision
        17,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18) || defined(DEMO_CASE))
    {
        staticRefIn0Case18, // Input vector 0
        staticRefIn1Case18, // Input vector 1
        staticRefOutCase18, // Output vector
        2048,               // length of vector
        MATHLIB_FLOAT64,    // precision
        18,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19))
    {
        staticRefIn0Case19, // Input vector 0
        staticRefIn1Case19, // Input vector 1
        staticRefOutCase19, // Output vector
        10240,              // length of vector
        MATHLIB_FLOAT64,    // precision
        19,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20))
    {
        staticRefIn0Case20, // Input vector 0
        staticRefIn1Case20, // Input vector 1
        staticRefOutCase20, // Output vector
        550,                // length of vector
        MATHLIB_FLOAT64,    // precision
        20,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21))
    {
        staticRefIn0Case21, // Input vector 0
        staticRefIn1Case21, // Input vector 1
        staticRefOutCase21, // Output vector
        1090,               // length of vector
        MATHLIB_FLOAT64,    // precision
        21,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22))
    {
        staticRefIn0Case22, // Input vector 0
        staticRefIn1Case22, // Input vector 1
        staticRefOutCase22, // Output vector
        2500,               // length of vector
        MATHLIB_FLOAT64,    // precision
        22,                 // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void MATHLIB_atan2_getTestParams(MATHLIB_atan2_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(MATHLIB_atan2_testParams_t);
}
