// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0
#include "MATHLIB_asin_testParams.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1) || defined(DEMO_CASE))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2) || defined(DEMO_CASE))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3) || defined(DEMO_CASE))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4) || defined(DEMO_CASE))
#include "test_data/staticRefCase4.h"
#endif

static MATHLIB_asin_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1) || defined(DEMO_CASE))
    {
        staticRefInCase1,  // Input vector
        staticRefOutCase1, // Output vector
        512,               // length of vector
        MATHLIB_FLOAT32,   // precision
        1,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2) || defined(DEMO_CASE))
    {
        staticRefInCase2,  // Input vector
        staticRefOutCase2, // Output vector
        1024,              // length of vector
        MATHLIB_FLOAT32,   // precision
        2,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3) || defined(DEMO_CASE))
    {
        staticRefInCase3,  // Input vector
        staticRefOutCase3, // Output vector
        2048,              // length of vector
        MATHLIB_FLOAT32,   // precision
        3,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4) || defined(DEMO_CASE))
    {
        staticRefInCase4,  // Input vector
        staticRefOutCase4, // Output vector
        15,                // length of vector
        MATHLIB_FLOAT32,   // precision
        4,                 // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void MATHLIB_asin_getTestParams(MATHLIB_asin_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(MATHLIB_asin_testParams_t);
}
