// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0
#include "MATHLIB_log10_testParams.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1) || defined(DEMO_CASE))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2) || defined(DEMO_CASE))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3) || defined(DEMO_CASE))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4) || defined(DEMO_CASE))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5) || defined(DEMO_CASE))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6) || defined(DEMO_CASE))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7) || defined(DEMO_CASE))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8) || defined(DEMO_CASE))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9) || defined(DEMO_CASE))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10) || defined(DEMO_CASE))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11) || defined(DEMO_CASE))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12) || defined(DEMO_CASE))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13) || defined(DEMO_CASE))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14) || defined(DEMO_CASE))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15) || defined(DEMO_CASE))
#include "test_data/staticRefCase15.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16) || defined(DEMO_CASE))
#include "test_data/staticRefCase16.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17) || defined(DEMO_CASE))
#include "test_data/staticRefCase17.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18) || defined(DEMO_CASE))
#include "test_data/staticRefCase18.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19) || defined(DEMO_CASE))
#include "test_data/staticRefCase19.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20) || defined(DEMO_CASE))
#include "test_data/staticRefCase20.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21) || defined(DEMO_CASE))
#include "test_data/staticRefCase21.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22) || defined(DEMO_CASE))
#include "test_data/staticRefCase22.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23) || defined(DEMO_CASE))
#include "test_data/staticRefCase23.h"
#endif

static MATHLIB_log10_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1) || defined(DEMO_CASE))
    {
        staticRefInCase1,  // Input vector
        staticRefOutCase1, // Output vector
        1,                 // length of vector
        MATHLIB_FLOAT32,   // precision
        1,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2) || defined(DEMO_CASE))
    {
        staticRefInCase2,  // Input vector
        staticRefOutCase2, // Output vector
        16,                // length of vector
        MATHLIB_FLOAT32,   // precision
        2,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3) || defined(DEMO_CASE))
    {
        staticRefInCase3,  // Input vector
        staticRefOutCase3, // Output vector
        32,                // length of vector
        MATHLIB_FLOAT32,   // precision
        3,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4) || defined(DEMO_CASE))
    {
        staticRefInCase4,  // Input vector
        staticRefOutCase4, // Output vector
        50,                // length of vector
        MATHLIB_FLOAT32,   // precision
        4,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5) || defined(DEMO_CASE))
    {
        staticRefInCase5,  // Input vector
        staticRefOutCase5, // Output vector
        64,                // length of vector
        MATHLIB_FLOAT32,   // precision
        5,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6) || defined(DEMO_CASE))
    {
        staticRefInCase6,  // Input vector
        staticRefOutCase6, // Output vector
        100,               // length of vector
        MATHLIB_FLOAT32,   // precision
        6,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7) || defined(DEMO_CASE))
    {
        staticRefInCase7,  // Input vector
        staticRefOutCase7, // Output vector
        128,               // length of vector
        MATHLIB_FLOAT32,   // precision
        7,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8) || defined(DEMO_CASE))
    {
        staticRefInCase8,  // Input vector
        staticRefOutCase8, // Output vector
        256,               // length of vector
        MATHLIB_FLOAT32,   // precision
        8,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9) || defined(DEMO_CASE))
    {
        staticRefInCase9,  // Input vector
        staticRefOutCase9, // Output vector
        512,               // length of vector
        MATHLIB_FLOAT32,   // precision
        9,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10) || defined(DEMO_CASE))
    {
        staticRefInCase10,  // Input vector
        staticRefOutCase10, // Output vector
        1024,               // length of vector
        MATHLIB_FLOAT32,    // precision
        10,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11) || defined(DEMO_CASE))
    {
        staticRefInCase11,  // Input vector
        staticRefOutCase11, // Output vector
        2048,               // length of vector
        MATHLIB_FLOAT32,    // precision
        11,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12) || defined(DEMO_CASE))
    {
        staticRefInCase12,  // Input vector
        staticRefOutCase12, // Output vector
        1,                  // length of vector
        MATHLIB_FLOAT64,    // precision
        12,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13) || defined(DEMO_CASE))
    {
        staticRefInCase13,  // Input vector
        staticRefOutCase13, // Output vector
        15,                 // length of vector
        MATHLIB_FLOAT64,    // precision
        13,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14) || defined(DEMO_CASE))
    {
        staticRefInCase14,  // Input vector
        staticRefOutCase14, // Output vector
        16,                 // length of vector
        MATHLIB_FLOAT64,    // precision
        14,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15) || defined(DEMO_CASE))
    {
        staticRefInCase15,  // Input vector
        staticRefOutCase15, // Output vector
        32,                 // length of vector
        MATHLIB_FLOAT64,    // precision
        15,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 16) || defined(DEMO_CASE))
    {
        staticRefInCase16,  // Input vector
        staticRefOutCase16, // Output vector
        50,                 // length of vector
        MATHLIB_FLOAT64,    // precision
        16,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 17) || defined(DEMO_CASE))
    {
        staticRefInCase17,  // Input vector
        staticRefOutCase17, // Output vector
        64,                 // length of vector
        MATHLIB_FLOAT64,    // precision
        17,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 18) || defined(DEMO_CASE))
    {
        staticRefInCase18,  // Input vector
        staticRefOutCase18, // Output vector
        100,                // length of vector
        MATHLIB_FLOAT64,    // precision
        18,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 19) || defined(DEMO_CASE))
    {
        staticRefInCase19,  // Input vector
        staticRefOutCase19, // Output vector
        128,                // length of vector
        MATHLIB_FLOAT64,    // precision
        19,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 20) || defined(DEMO_CASE))
    {
        staticRefInCase20,  // Input vector
        staticRefOutCase20, // Output vector
        256,                // length of vector
        MATHLIB_FLOAT64,    // precision
        20,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 21) || defined(DEMO_CASE))
    {
        staticRefInCase21,  // Input vector
        staticRefOutCase21, // Output vector
        512,                // length of vector
        MATHLIB_FLOAT64,    // precision
        21,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 22) || defined(DEMO_CASE))
    {
        staticRefInCase22,  // Input vector
        staticRefOutCase22, // Output vector
        1024,               // length of vector
        MATHLIB_FLOAT64,    // precision
        22,                 // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 23) || defined(DEMO_CASE))
    {
        staticRefInCase23,  // Input vector
        staticRefOutCase23, // Output vector
        2048,               // length of vector
        MATHLIB_FLOAT64,    // precision
        23,                 // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void MATHLIB_log10_getTestParams(MATHLIB_log10_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(MATHLIB_log10_testParams_t);
}
