# Copyright (C) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import print_function
from subprocess import call
from sys import platform

import sys
import numpy as np
import csv

sys.path.append("../common")

import MATHLIB_utils
import file_io


def gen_testCaseParams(testParamsFile, currPrm):
    """Generate and write test case parameters to idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    testId = currPrm["ID"]
    dType = currPrm["dTypeIn"]
    length = currPrm["length"]
    testType = currPrm["testType"]
    demoCase = currPrm["demoCase"]

    if testType == "STATIC":
        inp = "staticRefInCase" + testId
        out = "staticRefOutCase" + testId
    else:
        inp = "NULL"
        out = "NULL"

    if demoCase == "true":
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d) || defined(DEMO_CASE))\n"
            % (int(testId))
        )
    else:
        testParamsFile.write(
            "#if (defined(ALL_TEST_CASES) || (TEST_CASE == %d))\n" % (int(testId))
        )

    testParamsFile.write("{\n")
    testParamsFile.write("%s, // Input vector \n" % ((inp)))
    testParamsFile.write("%s, // Output vector \n" % ((out)))
    testParamsFile.write("%s, // length of vector \n" % ((length)))
    testParamsFile.write("%s, // precision \n" % ((dType)))
    testParamsFile.write("%d, // test ID\n" % int(testId))
    testParamsFile.write("},\n")
    testParamsFile.write("#endif")
    testParamsFile.write("\n\n")


def gen_idat_file(testParamsFile, testCases):
    """Generate the idat file

    Args:
        param1 (file object): Input file object to idat.c file
        param2 (dict object): Dict object with test case parameter

    """

    fIn = open("../common/ti_lice_header_testParams.txt", "r")
    lines = fIn.readlines()
    fIn.close()
    testParamsFile.writelines(lines)
    includeString = '#include "MATHLIB_recip_testParams.h"'
    testParamsFile.writelines(includeString)
    testParamsFile.write("\n")
    testParamsFile.write("/*This file is autogenerated*/\n")
    testParamsFile.write("/*Please do not edit*/\n")
    testParamsFile.write("\n\n")
    # generate ifdefs for header files
    for testCase in testCases:
        if testCase["testType"] == "STATIC":
            MATHLIB_utils.gen_ifdefs(testParamsFile, testCase)

    # generate parameters for test cases
    testParamsFile.write("static MATHLIB_recip_testParams_t testParams[] =  ")
    testParamsFile.write("{\n")

    for testCase in testCases:
        gen_testCaseParams(testParamsFile, testCase)

    testParamsFile.write("};\n\n")
    fIn = open("test_param_function.txt", "r")
    lines = fIn.readlines()

    testParamsFile.writelines(lines)


def process_test_case(testCase):
    """Convert str to int for necessary parameters

    Args:
        Param1(:obj: dict) : Dictionary object with test case parameters

    Returns:
        Obj: Dictionary object with necessary parameters converted to int

    """

    testCase["testId"] = int(testCase["ID"])
    testCase["length"] = int(testCase["length"])

    return testCase


def gen_test_case_header_file(testCase):
    """Generate test case and write out input and output tensors
    into a header file usable in C/C++ code.

    Args:
        param1 (:obj: dict): A dict object with all the test case
        parameters

    Returns:
        [int int]: Minimum and maximum value in output tensor

    """

    ##############################
    # Get test parameter of case #
    ##############################

    testId = testCase["ID"]
    length = testCase["length"]
    dTypeIn = testCase["dTypeIn"]

    # Generate input data: avoid zero to prevent divide-by-zero
    # Mix negative and positive values across a range
    half_len = int(length / 2)
    rem_len = length - half_len

    if dTypeIn == "MATHLIB_FLOAT32":
        # Negative values from -100 to -0.01
        in_neg = np.linspace(-100, -0.01, half_len).astype("float32")
        # Positive values from 0.01 to 100
        in_pos = np.linspace(0.01, 100, rem_len).astype("float32")
        input_data = np.concatenate([in_neg, in_pos]).astype("float32")
        np.random.shuffle(input_data)
    else:
        in_neg = np.linspace(-100, -0.01, half_len).astype("float64")
        in_pos = np.linspace(0.01, 100, rem_len).astype("float64")
        input_data = np.concatenate([in_neg, in_pos]).astype("float64")
        np.random.shuffle(input_data)

    # Compute reciprocal using numpy
    output_data = np.reciprocal(input_data)

    headerFileName = "staticRefCase" + str(testId) + ".h"
    file_io.write_header_file_single_input(
        input_data, output_data, testCase, headerFileName
    )

    return [np.min(output_data), np.max(output_data)]


# CSV file with parameters for all test cases
testCasesCsvFile = "test_cases_list.csv"
testIdList = []  # list of test IDs that we want to generate test data
testIdList += range(1, 13)


myArgs = MATHLIB_utils.getCmdLineArgs()


def gen_test_case(testCase):
    if testCase["testType"] == "STATIC":
        [minY, maxY] = gen_test_case_header_file(testCase)
        print(
            "Test case generation completed for test ID",
            testCase["ID"],
            "w/ min:",
            minY,
            "and max",
            maxY,
        )
    else:
        print(
            "Skipping test case generation for test ID",
            testCase["ID"],
            "as tesType is RANDOM",
        )


#############################################################################
# Open CSV file with test cases and generate header file with test data for #
# test cases of interest; based on testIdList                               #
#############################################################################

with open(testCasesCsvFile, encoding="utf-8-sig") as csv_file:
    testCaseReader = csv.DictReader(csv_file)
    testCases = list(testCaseReader)

    for testCase in testCases:
        testCase = process_test_case(testCase)

    for testCase in testCases:
        if myArgs.allCases == True:
            gen_test_case(testCase)
        elif int(testCase["ID"]) in testIdList:
            gen_test_case(testCase)


testParamsFileName = "../../MATHLIB_recip/MATHLIB_recip_testParams.cpp"


##########################################################################
# Generate idat.cpp file by parsing all the test cases in the CSV file  #
##########################################################################


with open(testParamsFileName, "w") as testParamsFile:
    gen_idat_file(testParamsFile, testCases)


# call(["clang-format", "-style=file", "-i", testParamsFileName])
if platform == "linux" or platform == "linux2":
    call(["indent", "-nut", "-i3", "-c55", "-l200", testParamsFileName])

call(["rm", testParamsFileName + "~"])  # remove backup file

print("Idat file generation completed")
